services:
  app:
    image: node:20
    container_name: circulation-app
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: node server.js
    ports:
      - "3006:3006"
    env_file:
      - .env
    restart: always
