services:
  app:
    image: node:20
    container_name: circulation-app
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: npm run start
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: always
